### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by ArthurGC** [ArthurGC/Api-webapp-capstone-project#21]
https://github.com/ArthurGC/Api-webapp-capstone-project/projects/1

Team:
- Ricardo Rodriguez R.
- Arthur Guzman

![cat-gif](https://raw.githubusercontent.com/ArthurGC/ArthurGC/main/public/cat-pc.gif)

**Comment by DeliceLydia** [comment]
## Hello Team, 

Good job so far! However, there are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- All cards have to be assigned to all team members this means we shall be able to see under each card an avatar of the students who were assigned to that specific card
- Cards should be assigned to team members in a fair way


### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the Issue thread if something is not clear 100%.

**Comment by henatan99** [comment]
- Hi team, well done. You have made the requested changes and your project is complete. You can proceed to the next milestone. :clap: :dancers:
